import type { Field, Event, SubscriberRegistration, SubscriberHandler, FieldChangeCallback } from "./core/types.ts";
import type { Chain, ChainLink, SubscriberContext, SubscriberError, PriorityHint, Delta } from "./core/types.ts";
import type { SystemConfig, System, TickResult } from "./core/system.ts";
import type { SubscriptionBuilder } from "./core/subscribe.ts";
import type { StateShape } from "./core/types.ts";
export { field } from "./core/field.ts";
export { event } from "./core/event.ts";
export { createSystem, useSystem, getSystem } from "./core/system.ts";
export { flow } from "./view/flow.ts";
export { setModelDebounce } from "./view/bindings.ts";
export { Ok, Err } from "./core/types.ts";
export type { Result, OkResult, ErrResult } from "./core/types.ts";
export declare function subscribe<E>(evt: Event<E>, handler: SubscriberHandler<E, any>): SubscriptionBuilder<any>;
export type { Field, Event, Chain, ChainLink, SubscriberContext, SubscriberError, PriorityHint, Delta, FieldChangeCallback, SubscriptionBuilder, SubscriberRegistration, SubscriberHandler, SystemConfig, System, TickResult, StateShape, };
